/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AudioSeparatorImport } from './routes/audio-separator'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AudioSeparatorRoute = AudioSeparatorImport.update({
  id: '/audio-separator',
  path: '/audio-separator',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/audio-separator': {
      id: '/audio-separator'
      path: '/audio-separator'
      fullPath: '/audio-separator'
      preLoaderRoute: typeof AudioSeparatorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-separator': typeof AudioSeparatorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-separator': typeof AudioSeparatorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/audio-separator': typeof AudioSeparatorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audio-separator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audio-separator'
  id: '__root__' | '/' | '/audio-separator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioSeparatorRoute: typeof AudioSeparatorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioSeparatorRoute: AudioSeparatorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/audio-separator"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/audio-separator": {
      "filePath": "audio-separator.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
